import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import axios from "axios";
import { FiTarget, FiActivity, FiUser, FiCode } from "react-icons/fi";

export default function PublicProfile() {
  const { username } = useParams();
  const [profile, setProfile] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await axios.get(`http://localhost:5000/api/public/${username}`);
        setProfile(response.data.data);
      } catch (err) {
        console.error("Failed to load profile", err);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, [username]);

  if (loading) return <div className="flex justify-center items-center h-screen"><p className="text-xl animate-pulse">Loading developer profile...</p></div>;
  if (!profile) return <div className="text-center p-20 text-red-500">Profile Not Found</div>;

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-10 px-4 flex justify-center text-gray-800 dark:text-gray-200">
      <div className="max-w-4xl w-full bg-white dark:bg-gray-800 rounded-[2rem] shadow-xl overflow-hidden animate-in slide-in-from-bottom-8 duration-500">
        
        {/* Header Cover */}
        <div className="h-40 bg-gradient-to-r from-blue-600 to-indigo-700 w-full relative">
          <div className="absolute -bottom-12 left-10 w-24 h-24 bg-white dark:bg-gray-800 rounded-full flex items-center justify-center shadow-lg border-4 border-white dark:border-gray-800">
            <FiUser className="text-4xl text-indigo-500" />
          </div>
        </div>

        <div className="pt-16 pb-8 px-10">
          <h1 className="text-3xl font-extrabold flex items-center gap-2 mb-1">
            Software Developer Portfolio 🚀
          </h1>
          <p className="text-gray-500 font-medium mb-6">Generated by StudentTwin AI</p>
          
          <div className="flex gap-4 mb-10">
            <div className="bg-indigo-50 dark:bg-gray-700 px-5 py-2 rounded-xl text-center">
              <p className="text-xs font-bold text-indigo-500 uppercase tracking-wide">XP</p>
              <p className="font-extrabold text-2xl">{profile.xp}</p>
            </div>
            <div className="bg-orange-50 dark:bg-gray-700 px-5 py-2 rounded-xl text-center">
              <p className="text-xs font-bold text-orange-500 uppercase tracking-wide">Streak</p>
              <p className="font-extrabold text-2xl">{profile.streak} Days</p>
            </div>
            <div className="bg-green-50 dark:bg-gray-700 px-5 py-2 rounded-xl text-center">
              <p className="text-xs font-bold text-green-500 uppercase tracking-wide">Readiness</p>
              <p className="font-extrabold text-2xl">{profile.readiness}%</p>
            </div>
          </div>

          {profile.badges && profile.badges.length > 0 && (
            <div className="mt-2 mb-8 flex flex-wrap gap-3 items-center">
              <span className="text-xs uppercase tracking-widest font-black text-gray-500 mr-2">Achievements</span>
              {profile.badges.map(b => (
                <div key={b.id} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-bold shadow-sm ${b.color.includes('bg-') ? b.color : 'bg-white border border-gray-200'}`}>
                  <span>{b.icon}</span>
                  <span>{b.name}</span>
                </div>
              ))}
            </div>
          )}

          <div className="bg-gradient-to-r from-gray-100 to-gray-50 dark:from-gray-700 dark:to-gray-800 p-6 rounded-2xl mb-8 border border-gray-200 dark:border-gray-600 relative">
            <p className="absolute -top-3 left-4 bg-white dark:bg-gray-800 px-3 text-sm font-bold text-indigo-600 rounded-full border border-gray-200">AI Professional Summary</p>
            <p className="text-lg leading-relaxed">{profile.aiSummary}</p>
          </div>

          <div className="mt-8">
            <h3 className="text-xl font-bold flex items-center gap-2 mb-4 border-b pb-2">
              <FiCode className="text-indigo-500" /> Tech Stack
            </h3>
            <div className="space-y-4">
              {profile.skills.map((skill, idx) => (
                <div key={idx} className="flex justify-between items-center bg-gray-50 dark:bg-gray-700 p-4 rounded-xl">
                  <div>
                    <p className="font-bold text-lg">{skill.name}</p>
                    <p className="text-sm font-medium text-gray-500 pt-1 tracking-wide">{skill.level}</p>
                  </div>
                  <div className="w-1/2 bg-gray-200 dark:bg-gray-600 rounded-full h-3">
                    <div className="bg-blue-600 h-3 rounded-full" style={{ width: `${skill.score}%` }}></div>
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
