import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import axios from "axios";
import { FiCode, FiStar, FiAward, FiGithub, FiBook, FiActivity, FiUser } from "react-icons/fi";
import SkillChart from "../components/SkillChart";

export default function PublicProfile() {
  const { username } = useParams();
  const [profile, setProfile] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        const BACKEND = import.meta.env.VITE_API_URL || "http://localhost:5000/api";
        const response = await axios.get(`${BACKEND}/public/${username}`);
        setProfile(response.data.data);
      } catch (err) {
        console.error("Failed to load profile", err);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, [username]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-indigo-950 to-gray-900 flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-indigo-300 font-semibold">Loading portfolio…</p>
        </div>
      </div>
    );
  }

  if (!profile) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-indigo-950 to-gray-900 flex items-center justify-center text-white text-center px-4">
        <div>
          <div className="text-6xl mb-4">🔍</div>
          <h2 className="text-3xl font-extrabold mb-2">Profile not found</h2>
          <p className="text-indigo-300">No student profile for <strong>@{username}</strong></p>
        </div>
      </div>
    );
  }

  const readiness = profile.readiness || 0;
  const skills = profile.skills || [];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-indigo-950 to-gray-900">
      {/* Ambient glows */}
      <div className="fixed w-[500px] h-[500px] bg-indigo-600/10 rounded-full blur-3xl top-0 right-0 pointer-events-none" />
      <div className="fixed w-72 h-72 bg-purple-600/10 rounded-full blur-3xl bottom-0 left-0 pointer-events-none" />

      <div className="relative max-w-4xl mx-auto px-4 py-12">

        {/* ── HERO CARD ── */}
        <div className="bg-white/8 backdrop-blur-xl border border-white/15 rounded-3xl p-8 mb-5 text-white shadow-2xl">
          <div className="flex flex-col sm:flex-row items-start gap-6">
            {/* Avatar */}
            <div className="w-20 h-20 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl flex items-center justify-center text-3xl font-extrabold flex-shrink-0 shadow-xl shadow-indigo-500/30">
              {profile.name?.[0]?.toUpperCase() || "S"}
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex flex-col sm:flex-row sm:items-center gap-2 mb-1">
                <h1 className="text-3xl font-extrabold tracking-tight">{profile.name}'s Portfolio</h1>
              </div>
              <p className="text-indigo-400 text-sm mb-3 font-medium">@{username} · Generated by StudentTwin AI</p>
              {profile.summary && (
                <p className="text-indigo-100/80 text-sm leading-relaxed max-w-2xl">{profile.summary}</p>
              )}
            </div>
          </div>

          {/* Stats row */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-6">
            {[
              { label: "XP",        value: profile.xp || 0,      icon: FiStar },
              { label: "Streak",    value: `${profile.streak || 0}d`, icon: FiActivity },
              { label: "Skills",    value: skills.length,          icon: FiCode },
              { label: "Readiness", value: `${readiness}%`,        icon: FiAward },
            ].map(s => (
              <div key={s.label} className="bg-white/8 rounded-2xl p-4 text-center border border-white/10">
                <s.icon className="mx-auto text-indigo-300 mb-2" size={16} />
                <p className="text-xl font-extrabold">{s.value}</p>
                <p className="text-xs text-indigo-400 font-bold mt-0.5">{s.label}</p>
              </div>
            ))}
          </div>
        </div>

        {/* ── BADGES ── */}
        {profile.badges?.length > 0 && (
          <div className="bg-white/8 backdrop-blur-xl border border-white/15 rounded-2xl p-5 mb-5 text-white">
            <p className="text-xs font-black uppercase tracking-widest text-indigo-400 mb-3">Achievements</p>
            <div className="flex flex-wrap gap-2">
              {profile.badges.map(b => (
                <div key={b.id} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold ${b.color?.includes("bg-") ? b.color : "bg-white/10 border border-white/20 text-white"}`}>
                  <span>{b.icon}</span><span>{b.name}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── CAREER READINESS ── */}
        <div className="bg-white/8 backdrop-blur-xl border border-white/15 rounded-2xl p-6 mb-5 text-white">
          <div className="flex justify-between items-center mb-3">
            <span className="text-xs font-black uppercase tracking-widest text-indigo-400">Career Readiness</span>
            <span className="text-2xl font-extrabold">{readiness}%</span>
          </div>
          <div className="w-full bg-white/10 rounded-full h-3 overflow-hidden">
            <div
              className="h-3 rounded-full bg-gradient-to-r from-indigo-500 to-purple-500 transition-all duration-1000 shadow-lg"
              style={{ width: `${readiness}%` }}
            />
          </div>
          <p className="text-indigo-300/70 text-xs mt-2">
            {readiness >= 80 ? "🔥 Job-ready! Strong candidate for tech roles."
              : readiness >= 50 ? "⚡ Good progress — keep building skills."
              : "🌱 Early stage — great foundation forming."}
          </p>
        </div>

        {/* ── GITHUB ── */}
        {profile.githubUsername && (
          <div className="bg-white/8 backdrop-blur-xl border border-white/15 rounded-2xl p-5 mb-5 text-white">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-gray-800 rounded-xl flex items-center justify-center flex-shrink-0">
                  <FiGithub size={18} className="text-gray-300" />
                </div>
                <div>
                  <p className="font-bold">@{profile.githubUsername}</p>
                  <p className="text-xs text-indigo-300">{profile.githubRepos || 0} public repositories</p>
                </div>
              </div>
              <a
                href={`https://github.com/${profile.githubUsername}`}
                target="_blank" rel="noopener noreferrer"
                className="flex items-center gap-1.5 bg-white/10 hover:bg-white/20 text-white text-xs font-bold px-3 py-2 rounded-xl transition"
              >
                <FiBook size={12} /> View
              </a>
            </div>
          </div>
        )}

        {/* ── SKILL CHART ── */}
        {skills.length > 0 && (
          <div className="bg-white/8 backdrop-blur-xl border border-white/15 rounded-2xl p-6 mb-5 text-white">
            <p className="text-xs font-black uppercase tracking-widest text-indigo-400 mb-4 flex items-center gap-2">
              <FiCode size={11} /> Skills Overview
            </p>
            <SkillChart skills={skills} />
          </div>
        )}

        {/* ── SKILL BARS ── */}
        {skills.length > 0 && (
          <div className="bg-white/8 backdrop-blur-xl border border-white/15 rounded-2xl p-6 mb-5 text-white">
            <p className="text-xs font-black uppercase tracking-widest text-indigo-400 mb-5">Competency Breakdown</p>
            <div className="space-y-4">
              {[...skills].sort((a, b) => (b.score || 0) - (a.score || 0)).map((skill, i) => (
                <div key={skill.skill_name || i}>
                  <div className="flex justify-between text-sm mb-1.5">
                    <span className="font-semibold">{skill.skill_name}</span>
                    <span className={`font-extrabold text-xs ${
                      (skill.score || 0) >= 70 ? "text-emerald-400"
                      : (skill.score || 0) >= 40 ? "text-yellow-400"
                      : "text-red-400"
                    }`}>
                      {skill.score || 0}/100
                    </span>
                  </div>
                  <div className="w-full bg-white/10 rounded-full h-2 overflow-hidden">
                    <div
                      className={`h-2 rounded-full transition-all duration-700 ${
                        (skill.score || 0) >= 70 ? "bg-emerald-500"
                        : (skill.score || 0) >= 40 ? "bg-yellow-400"
                        : "bg-red-400"
                      }`}
                      style={{ width: `${skill.score || 0}%`, transitionDelay: `${i * 80}ms` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Footer */}
        <p className="text-center text-indigo-500/50 text-xs mt-6 font-medium">
          Built with StudentTwin · AI-powered student progress tracker
        </p>
      </div>
    </div>
  );
}
