module.exports = {
  "backend developer": [
    { day: 1, task: "Learn Java Basics" },
    { day: 2, task: "Learn OOP Concepts" },
    { day: 3, task: "Practice Java Problems" },
    { day: 4, task: "Introduction to SQL" },
    { day: 5, task: "Write SQL Queries" },
    { day: 6, task: "Learn Spring Boot Basics" },
    { day: 7, task: "Build Simple API" },
    { day: 8, task: "REST API Concepts" },
    { day: 9, task: "Database Integration" },
    { day: 10, task: "Mini Backend Project" },
    { day: 11, task: "Authentication (JWT)" },
    { day: 12, task: "Error Handling" },
    { day: 13, task: "Advanced SQL" },
    { day: 14, task: "Project Enhancement" },
    { day: 15, task: "Deploy Backend" },
    { day: 16, task: "Learn Node.js Basics" },
    { day: 17, task: "Express.js API" },
    { day: 18, task: "Middleware Concepts" },
    { day: 19, task: "Build CRUD API" },
    { day: 20, task: "API Testing (Postman)" },
    { day: 21, task: "Optimize Queries" },
    { day: 22, task: "Security Basics" },
    { day: 23, task: "System Design Basics" },
    { day: 24, task: "Build Full Backend Project" },
    { day: 25, task: "Resume Preparation" },
    { day: 26, task: "Mock Interviews" },
    { day: 27, task: "DSA Practice" },
    { day: 28, task: "Revise Concepts" },
    { day: 29, task: "Final Project Improvement" },
    { day: 30, task: "Portfolio + GitHub Cleanup" },
  ],
  "frontend developer": [
    { day: 1, task: "HTML Basics" },
    { day: 2, task: "CSS Fundamentals" },
    { day: 3, task: "JavaScript Basics" },
    { day: 4, task: "DOM Manipulation" },
    { day: 5, task: "Responsive Design" },
    { day: 6, task: "CSS Flexbox & Grid" },
    { day: 7, task: "JavaScript ES6+" },
    { day: 8, task: "React Basics" },
    { day: 9, task: "React Components" },
    { day: 10, task: "State Management" },
    { day: 11, task: "React Router" },
    { day: 12, task: "API Integration (Fetch/Axios)" },
    { day: 13, task: "Build Simple React App" },
    { day: 14, task: "Tailwind CSS" },
    { day: 15, task: "Build Portfolio Website" },
    { day: 16, task: "Testing Basics" },
    { day: 17, task: "Performance Optimization" },
    { day: 18, task: "TypeScript Basics" },
    { day: 19, task: "Next.js Introduction" },
    { day: 20, task: "Build Full Frontend Project" },
    { day: 21, task: "Accessibility (a11y)" },
    { day: 22, task: "Animation Libraries" },
    { day: 23, task: "State Management (Redux)" },
    { day: 24, task: "Build Dashboard UI" },
    { day: 25, task: "Code Review Practices" },
    { day: 26, task: "Resume Preparation" },
    { day: 27, task: "Mock Interviews" },
    { day: 28, task: "DSA Practice" },
    { day: 29, task: "Final Project Improvement" },
    { day: 30, task: "Portfolio + GitHub Cleanup" },
  ],
};
